services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      - start
      - --hostname-strict=false
      - --https-key-store-file=/etc/keycloak-keystore.jks
      - --import-realm
    ports:
      - "8443:8443"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - d:/tmp/keycloak-keystore.jks:/etc/keycloak-keystore.jks
      - d:/tmp/quarkus-realm.json:/opt/keycloak/data/import/quarkus-realm.json
    networks:
      - net
    restart: always
  resource-server-rest:
    container_name: resource-server-rest
    build:
      context: ..
      dockerfile: docker-config/Resource-Server-Rest.Dockerfile
    depends_on:
      - keycloak
    ports:
      - "8081:8081"
    networks:
      - net
    restart: unless-stopped
networks:
  net:
    driver: bridge